# Generated by Django 4.2.3 on 2023-07-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padron',
            options={'verbose_name': 'Padron', 'verbose_name_plural': 'Padrones'},
        ),
    ]
