# Generated by Django 4.2.3 on 2023-08-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0002_padron_ultima_consulta_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='padron',
            name='actividad_economica',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padron',
            name='comprobantes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
