# Generated by Django 4.2.3 on 2023-07-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0002_alter_padron_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='padron',
            name='domicilio_fiscal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='padron',
            name='ultima_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='padron',
            name='razon_social',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
