# Generated by Django 4.2.3 on 2023-07-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunat', '0003_padron_domicilio_fiscal_padron_ultima_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='padron',
            index=models.Index(fields=['razon_social', 'ruc'], name='sunat_padro_razon_s_83af26_idx'),
        ),
    ]
