# Generated by Django 4.2.3 on 2023-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('ruc', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('condicion', models.CharField(blank=True, max_length=255, null=True)),
                ('ubigeo', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
