name: loada padron sunat
on:
  workflow_dispatch: # run once time for month
  schedule:
    - cron: '0 0 1 * *'
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: validate environment variables
        run: |
          # djagno env variables
          if [ -z "${{ secrets.DJANGO_DEBUG }}" ]; then
            echo "DJANGO_DEBUG is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DJANGO_SECRET_KEY }}" ]; then
            echo "DJANGO_SECRET_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "DATABASE_URL is not set"
            exit 1
          fi
          
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django validate deploy
        run: python manage.py check --deploy

      - name: Django migrate
        run: python .\manage.py sunat --padron-sunat # --size=10000